variables:
  BUILD_OUTPUT_DIR: app/build/outputs/apk
  TESTS_XML_DIR: app/build/outputs/androidTest-results
  IMG_NAME: system-images;android-23;google_apis;x86
  DEVICE_TYPE: "Nexus 4"
  DEVICE_NAME: Nexus4Emu
  DEVICE_VIDEO_DIR: /mnt/sdcard/DCIM
  SEARCH_DIR: cliqzSearch

jobs:
- job: Build_Debug

  pool:
    vmImage: 'macOS 10.13'

  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - bash: |
      npm ci
      npm run build
    workingDirectory: $(SEARCH_DIR)
    displayName: 'Build search (debug)'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleDebug'
    displayName: 'Assemble Debug'

  - task: CopyFiles@2
    inputs:
      contents: '$(BUILD_OUTPUT_DIR)/**/*.apk'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(Build.BuildId).DebugBuilds'
      publishLocation: 'Container'

- job: Build_Release
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  pool:
    vmImage: 'macOS 10.13'

  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - bash: |
      npm ci
      npm run build:prod
    workingDirectory: $(SEARCH_DIR)
    displayName: 'Build search (release)'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: .sentry_token
    displayName: 'Download Sentry Token'

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Agent.TempDirectory)
      contents: '.sentry_token'
      targetFolder: $(Build.SourcesDirectory)
    displayName: 'Copy Sentry Token'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'assemble'
      options: '-PversionName=1.0.$(Build.BuildNumber)'
    displayName: 'Assemble Release'

  - task: AndroidSigning@2
    inputs:
      apkFiles: '$(BUILD_OUTPUT_DIR)/**/*.apk'
      jarsign: true
      jarsignerKeystoreFile: 'upload-keystore.jks'
      jarsignerKeystorePassword: '$(keystore-password)'
      jarsignerKeystoreAlias: 'upload'
      jarsignerKeyPassword: '$(upload-key-password)'
      zipalign: true
      zipalignFile: '/Users/vsts/Library/Android/sdk/build-tools/28.0.3/zipalign'

  - task: CopyFiles@2
    inputs:
      contents: '$(BUILD_OUTPUT_DIR)/**/*.apk'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(Build.BuildId).ReleaseBuilds'
      publishLocation: 'Container'

- job: Test

  pool:
    vmImage: 'macOS 10.13'

  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - bash: |
      npm ci
      npm run build
    workingDirectory: $(SEARCH_DIR)
    displayName: 'Build search'

  - bash: |
      printf "127.0.0.1\tanolysis.cliqz.com\n127.0.0.1\tstats.cliqz.com\n" >> /etc/hosts
      $ANDROID_HOME/tools/bin/sdkmanager "$(IMG_NAME)"
      $ANDROID_HOME/tools/bin/avdmanager create avd --device "$(DEVICE_TYPE)" --package "$(IMG_NAME)" --abi google_apis/x86 --name "$(DEVICE_NAME)"
      $ANDROID_HOME/emulator/emulator -avd $(DEVICE_NAME) &
      echo $! > emu.pid
      echo "Emulator Started with Process ID: $(cat emu.pid)"
      $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      sleep 60
      $ANDROID_HOME/platform-tools/adb devices
    displayName: 'Setup and Launch Emulator'

  - bash: |
      $ANDROID_HOME/platform-tools/adb shell """
      mount -o rw,remount rootfs /;
      chmod 0777 /mnt/sdcard;
      exit
      """
      sleep 10
      $ANDROID_HOME/platform-tools/adb logcat -c
      $ANDROID_HOME/platform-tools/adb logcat > $(Build.ArtifactStagingDirectory)/device.log &
      echo $! > logcat.pid
      echo "Logcat Started with Process ID: $(cat logcat.pid)"
      $ANDROID_HOME/platform-tools/adb shell "mkdir -p $(DEVICE_VIDEO_DIR)"
      $ANDROID_HOME/platform-tools/adb shell '''
        for i in $(seq 1 1 20)
        do
          screenrecord --bugreport --verbose --time-limit=180 /mnt/sdcard/DCIM/test"${i}".mp4
        done
      ''' > $(Build.ArtifactStagingDirectory)/video.log &
      echo $! > video.pid
      echo "Video Recorder Started with Process ID: $(cat video.pid)"
    displayName: 'Start Video Record and Logcat'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      publishJUnitResults: true
      testResultsFiles: '$(TESTS_XML_DIR)/**/TEST-*.xml'
      tasks: 'connectedX86DebugAndroidTest'
    displayName: 'Run Tests'

  - bash: |
      kill -9 $(cat video.pid) || true
      sleep 10
      $ANDROID_HOME/platform-tools/adb pull $(DEVICE_VIDEO_DIR)/ $(Build.ArtifactStagingDirectory)/ || true
      kill -9 $(cat logcat.pid) || true
      adb kill-server
      kill -9 $(cat emu.pid)
    condition: or(succeeded(), failed())
    displayName: 'Copy Videos and Clean Up'

  - task: PublishBuildArtifacts@1
    condition: or(succeeded(), failed())
    displayName: 'Publish'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(Build.BuildId).Test'
      publishLocation: 'Container'
